spring.application.name=CivicSync_Backend
# 🔌 Server Port Config (Runs your Java API on port 8080)
server.port=8080

# 🗄️ Database Connection URL String
spring.datasource.url=jdbc:postgresql://localhost:5432/civic_sync_db
spring.datasource.username=postgres
spring.datasource.password=li@17

# 🏗️ Hibernate & JPA Engines Strategy
# "update" tells Spring to automatically create tables/columns if they are missing
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 📜 Debugging: Show the active SQL queries inside IntelliJ's console terminal
spring.jpa.show-sql=true
# Increase max file upload sizes (e.g., 50MB for video captures)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lingeshprt2008@gmail.com
# ⚠️ Note: This must be a Google "App Password", NOT your account password
spring.mail.password=wdnkbgkngvjvhluo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
